### ISSUE TITLE
Handle errors on updating grafana notification policies

### ISSUE THREAD

**Issue by dsimog01** [dappnode/monitor-service#36]
The code for updating notification policies is not handling if the response code is OK. The HTTP PUT request might be failing and we would not notice:

https://github.com/dappnode/monitor-service/pull/34/files#diff-fd43ce3865ba820b80036ab34fae6739e66e8a06f948be9bfcf744dd0b9d2f90R94

**Comment by pablomendezroyo** [comment]
Implemented
